// src/constants/chatConstants.js

export const CHAT_GET_HISTORY_REQUEST = 'CHAT_GET_HISTORY_REQUEST';
export const CHAT_GET_HISTORY_SUCCESS = 'CHAT_GET_HISTORY_SUCCESS';
export const CHAT_GET_HISTORY_FAIL = 'CHAT_GET_HISTORY_FAIL';

export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAIL = 'CHAT_SEND_MESSAGE_FAIL';

export const CLEAR_CHAT_MESSAGES = 'CLEAR_CHAT_MESSAGES';

export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_FAIL = 'FETCH_CONVERSATIONS_FAIL';
export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST';