export const JOB_TYPE_LOAD_REQUEST = "JOB_TYPE_LOAD_REQUEST";
export const JOB_TYPE_LOAD_SUCCESS = "JOB_TYPE_LOAD_SUCCESS";
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL";
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET";

export const JOB_TYPE_UPDATE_REQUEST = "JOB_TYPE_UPDATE_REQUEST";
export const JOB_TYPE_UPDATE_SUCCESS = "JOB_TYPE_UPDATE_SUCCESS";
export const JOB_TYPE_UPDATE_FAIL = "JOB_TYPE_UPDATE_FAIL";
export const JOB_TYPE_UPDATE_RESET = "JOB_TYPE_UPDATE_RESET";

export const JOB_TYPE_SINGLE_REQUEST=" JOB_TYPE_SINGLE_REQUEST";
export const JOB_TYPE_SINGLE_SUCCESS = "JOB_TYPE_SINGLE_SUCCESS";
export const JOB_TYPE_SINGLE_FAIL = "JOB_TYPE_SINGLE_FAIL";
export const JOB_TYPE_SINGLE_RESET = "JOB_TYPE_SINGLE_RESET";

export const CREATE_JOB_TYPE_REQUEST = "CREATE_JOB_TYPE_REQUEST";
export const CREATE_JOB_TYPE_SUCCESS = "CREATE_JOB_TYPE_SUCCESS";
export const CREATE_JOB_TYPE_FAIL = "CREATE_JOB_TYPE_FAIL";
export const CREATE_JOB_TYPE_RESET = "CREATE_JOB_TYPE_RESET";

export const DELETE_JOB_TYPE_REQUEST = "DELETE_JOB_TYPE_REQUEST";
export const DELETE_JOB_TYPE_SUCCESS = "DELETE_JOB_TYPE_SUCCESS";
export const DELETE_JOB_TYPE_FAIL = "DELETE_JOB_TYPE_FAIL";
export const DELETE_JOB_TYPE_RESET = "DELETE_JOB_TYPE_RESET";

